# Generated by Django 6.0.7 on 2026-08-07 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Server')),
                ('hostname', models.CharField(max_length=100)),
                ('cpu_load', models.PositiveSmallIntegerField(null=True)),
                ('ram_load', models.PositiveSmallIntegerField(null=True)),
                ('disc_load', models.PositiveSmallIntegerField(null=True)),
                ('status', models.CharField(choices=[('OFF', 'Offline'), ('ON', 'Online')], default='OFF')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
