# Generated by Django 6.0.7 on 2026-08-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='disc_load',
        ),
    ]
