# Generated by Django 6.0.7 on 2026-08-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agent_disc_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='output',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
