# Generated by Django 6.0.7 on 2026-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_command_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
