# Generated by Django 6.0.7 on 2026-08-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_command_finished_at_command_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='output',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
