# Generated by Django 6.0.7 on 2026-08-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_command_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='errors',
            field=models.JSONField(default=dict),
        ),
    ]
