# Generated by Django 6.0.7 on 2026-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_command_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='output',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
