# Generated by Django 6.0.7 on 2026-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_command_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='os',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
