# Generated by Django 6.0.7 on 2026-08-29 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agent_ip_agent_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_load', models.PositiveSmallIntegerField(null=True)),
                ('ram_load', models.PositiveSmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Metrics',
            },
        ),
    ]
