# Generated by Django 6.0.7 on 2026-08-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agentmetrics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentMetrics',
            new_name='AgentMetric',
        ),
    ]
