# Generated by Django 6.0.7 on 2026-08-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_rename_agentmetrics_agentmetric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentmetric',
            old_name='agent_id',
            new_name='agent',
        ),
    ]
