# Generated by Django 6.0.7 on 2026-08-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_rename_agent_id_agentmetric_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmetric',
            options={'verbose_name': 'Metric'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='agentmetric',
            index=models.Index(fields=['agent', '-created_at'], name='agents_agen_agent_i_605abf_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['agent', 'status'], name='agents_comm_agent_i_e62257_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['agent', '-created_at'], name='agents_comm_agent_i_7c1257_idx'),
        ),
    ]
