# Generated by Django 6.0.7 on 2026-09-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_alter_agentmetric_options_alter_agent_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='errors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='command',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='output',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='command',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING'),
        ),
    ]
