# Generated by Django 6.0.7 on 2026-09-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_alter_command_errors_alter_command_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmetric',
            options={'verbose_name': 'Metric', 'verbose_name_plural': 'Metrics'},
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='cpu_load_per_core',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='disk_read_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='disk_write_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='gpu_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='gpu_memory_total_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='gpu_memory_used_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='load_average',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='network_drops',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='network_errors',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='network_rx_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='network_rx_packets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='network_tx_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='network_tx_packets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='ram_available_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='ram_used_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='swap_available_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='swap_used_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='temperatures',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agentmetric',
            name='cpu_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentmetric',
            name='ram_load',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
