# Generated by Django 6.0.7 on 2026-09-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_alter_agentmetric_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmetric',
            options={},
        ),
        migrations.RenameField(
            model_name='agentmetric',
            old_name='temperatures',
            new_name='cpu_metrics',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='cpu_load',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='cpu_load_per_core',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='disk_read_bytes',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='disk_write_bytes',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='gpu_load',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='gpu_memory_total_bytes',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='gpu_memory_used_bytes',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='load_average',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='network_drops',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='network_errors',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='network_rx_bytes',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='network_rx_packets',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='network_tx_bytes',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='network_tx_packets',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='ram_available_bytes',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='ram_load',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='ram_used_bytes',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='swap_available_bytes',
        ),
        migrations.RemoveField(
            model_name='agentmetric',
            name='swap_used_bytes',
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='gpu_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='memory_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='network_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='storage_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='thermal_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
