# Generated by Django 6.0.7 on 2026-09-20 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_alter_agentmetric_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cpu_load',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='Server', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='os',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='ram_load',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('OFF', 'Offline'), ('ON', 'Online')], default='OFF', max_length=3),
        ),
        migrations.AlterField(
            model_name='agent',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
