# Generated by Django 6.0.7 on 2026-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_alter_agent_cpu_load_alter_agent_name_alter_agent_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cpu_load',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='ram_load',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
